Clone https://github.com/jfhealthcare/Chexpert and move CheXpert dataset inside this directory
Inference for 5 classes with pretrained weights

In [1]:
import torch
from easydict import EasyDict as edict
import json
from torch.nn import DataParallel
from model.classifier import Classifier
import time

# model = torch.load("config/pre_train.pth", map_location=torch.device('cpu'))

/Users/suzannenie/Library/Python/myvenv3/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
cfg_path = "config/example.json"
pre_train = "config/pre_train.pth"

with open(cfg_path) as f:
    cfg = edict(json.load(f))
    # print(json.dumps(cfg, indent=4))

# device_ids = list(map(int, args.device_ids.split(',')))
device_ids = []
num_devices = torch.cuda.device_count()
device = torch.device('cpu')
# device = torch.device('cuda:{}'.format(device_ids[0]))


model = Classifier(cfg)
model = DataParallel(model, device_ids=device_ids).to(device).train()
ckpt = torch.load(pre_train, map_location=device)
model.module.load_state_dict(ckpt)

<All keys matched successfully>

In [3]:
from torch.utils.data import DataLoader
from data.dataset import ImageDataset
import numpy as np

dataloader = DataLoader(
    ImageDataset(cfg["dev_csv"], cfg, mode='heatmap'),
    batch_size=1, num_workers=4,
    drop_last=False, shuffle=False)

In [4]:
torch.set_grad_enabled(False)
model.eval()
device = torch.device('cpu')
steps = len(dataloader)
dataiter = iter(dataloader)
num_tasks = len(cfg.num_classes)
txt_file = "plot.txt"

test_header = [
    'Path',
    'Cardiomegaly',
    'Edema',
    'Consolidation',
    'Atelectasis',
    'Pleural Effusion']

In [5]:
def get_pred(output, cfg):
    if cfg.criterion == 'BCE' or cfg.criterion == "FL":
        for num_class in cfg.num_classes:
            assert num_class == 1
        pred = torch.sigmoid(output.view(-1)).cpu().detach().numpy()
    elif cfg.criterion == 'CE':
        for num_class in cfg.num_classes:
            assert num_class >= 2
        prob = F.softmax(output)
        pred = prob[:, 1].cpu().detach().numpy()
    else:
        raise Exception('Unknown criterion : {}'.format(cfg.criterion))

    return pred

In [6]:
print(','.join(test_header) + '\n')
print("steps", steps, "num_tasks", num_tasks)
steps = 5
images = []

for step in range(steps):
    print("step ", step)
    image, path, labels = next(dataiter)
    image = image.to(device)
    output, __ = model(image)
    batch_size = len(path)
    pred = np.zeros((num_tasks, batch_size))

    for i in range(num_tasks):
        pred[i] = get_pred(output[i], cfg)

    for i in range(batch_size):
        batch = ','.join(map(lambda x: '{}'.format(x), pred[:, i]))
        result = path[i] + ',' + batch
        print(result + '\n')
        print('{}, Image : {}, Prob : {}, labels : {} '.format(
            time.strftime("%Y-%m-%d %H:%M:%S"), path[i], batch, labels))
        print('\n\n')
        images.append(path[i])
        

Path,Cardiomegaly,Edema,Consolidation,Atelectasis,Pleural Effusion

steps 234 num_tasks 5
step  0


RuntimeError: Given groups=1, weight of size [1, 2048, 1, 1], expected input[1, 1024, 16, 16] to have 2048 channels, but got 1024 channels instead

In [ ]:
from util.heatmaper import Heatmaper 
# Heatmaper = None

disease_classes = [
    'Cardiomegaly',
    'Edema',
    'Consolidation',
    'Atelectasis',
    'Pleural Effusion'
]
plot_path = "plots"
alpha = 0.2
prefix = "none"

cfg["global_pool"] = "AVG_MAX"

# create plot folder
if not os.path.exists(plot_path):
    os.mkdir(plot_path)
# construct heatmap_cfg
heatmaper = Heatmaper(alpha, prefix, cfg, model, device)
assert prefix in ['none', *(disease_classes)]
with open(txt_file) as f:
    # for line in f:
    for line in images:
        time_start = time.time()
        jpg_file = line.strip('\n')
        print(jpg_file)
        prefix, figure_data = heatmaper.gen_heatmap(jpg_file)
        bn = os.path.basename(jpg_file)
        save_file = '{}/{}{}'.format(plot_path, prefix, bn)
        assert cv2.imwrite(save_file, figure_data), "write failed!"
        time_spent = time.time() - time_start
        print(
            '{}, {}, heatmap generated, Run Time : {:.2f} sec'
            .format(time.strftime("%Y-%m-%d %H:%M:%S"),
                    jpg_file, time_spent))

CheXpert-v1.0-small/valid/patient64541/study1/view1_frontal.jpg
torch.Size([1, 3, 512, 512]) (320, 390, 3)
[tensor([[0.4413]]), tensor([[0.0234]]), tensor([[-1.1419]]), tensor([[-0.1762]]), tensor([[-1.9679]])] []


RuntimeError: stack expects a non-empty TensorList

In [ ]:
import cv2
from data.utils import transform

In [ ]:
image_file = images[0]

image_gray = cv2.imread(image_file, 0)
assert image_gray is not None, "invalid image read in: {}"\
    .format(image_file)
image_color = cv2.cvtColor(image_gray, cv2.COLOR_GRAY2RGB)
image = transform(image_gray, cfg)
image = torch.from_numpy(image)
image = image.unsqueeze(0)
print(image.shape)
print(image_color.shape)

torch.Size([1, 3, 512, 512])
(320, 390, 3)


In [ ]:
model(image)

([tensor([[-2.9403]]),
  tensor([[-0.3623]]),
  tensor([[-1.0317]]),
  tensor([[-0.6134]]),
  tensor([[-2.3091]])],
 [])